
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "BridgeMembersStore": "app/view/tabs/NetworkTab.js",
  "Ext": "ext/src",
  "Onc.core.manager.ComputeManager": "app/core/manager/Copy of ComputeManager.js",
  "Onc.core.ui.widgets.TagBox": "app/core/ui/widgets/Tagger.js",
  "Onc.core.ui.widgets.TagModel": "app/core/ui/widgets/Tagger.js",
  "Onc": "app",
  "Ext.ux.GroupTreeChunker": "ext/src/ux/GroupTabPanel.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "Onc.model.IpRoute": [],
  "Onc.model.Task": [],
  "Onc.model.ManagedNode": [],
  "Onc.view.compute.EditVmView": [],
  "Onc.controller.TasksController": [],
  "Ext.ux.grid.TransformGrid": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Onc.store.VmGridTypeStore": [],
  "Onc.model.Hangar": [],
  "Onc.store.VirtualizationContainerStore": [],
  "Onc.model.NetworkInterface": [],
  "Onc.portal.GaugesChartPortlet": [],
  "Onc.store.TasksPortletStore": [],
  "Onc.portal.LogPortlet": [],
  "Onc.model.VmProfile": [],
  "Ext.ux.event.Driver": [],
  "Ext.ux.ajax.XmlSimlet": [],
  "Onc.store.VmProfilesStore": [],
  "Onc.store.SearchResultsStore": [],
  "Onc.view.compute.ComputeView": [],
  "Onc.core.ui.components.NetworkGauge": [],
  "Ext.ux.DataView.DragSelector": [],
  "Onc.view.compute.GaugesChartView": [],
  "Onc.store.TasksStore": [],
  "Onc.view.compute.ZabbixRegistrationView": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Onc.portal.Portlet": [],
  "Onc.view.TasksView": [],
  "Onc.store.TemplatesStore": [],
  "Onc.view.NotificationBarView": [],
  "Ext.ux.form.MultiSelect": [
    "Ext.ux.Multiselect"
  ],
  "Onc.core.ui.widgets.GaugeChart": [],
  "Onc.store.AllocationPolicyStore": [],
  "Onc.model.Command": [],
  "Onc.model.Compute": [],
  "Onc.model.NetworkInterfaces": [],
  "Ext.ux.CheckColumn": [],
  "Ext.ux.PreviewPlugin": [],
  "Onc.portal.TasksPortlet": [],
  "Onc.model.ZabbixHostgroup": [],
  "Onc.store.VmGridStore": [],
  "Onc.core.ui.components.ComputeGauge": [],
  "Onc.store.ZabbixHostgroupsStore": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.event.RecorderManager": [],
  "Onc.store.ComputesStore": [],
  "Onc.model.AuthenticatedUser": [],
  "Onc.view.tabs.SystemTab": [],
  "Ext.ux.ProgressBarPager": [],
  "Onc.core.ui.widgets.Gauge": [],
  "Ext.ux.ajax.Simlet": [],
  "Ext.ux.SlidingPager": [],
  "Onc.core.Store": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [],
  "Onc.controller.InfrastructureJoinController": [],
  "Onc.controller.RetryController": [],
  "Onc.controller.LoginController": [],
  "Onc.core.EventBus": [],
  "Ext.ux.event.Recorder": [],
  "Onc.portal.InfoBoxesPortlet": [],
  "Onc.view.compute.NewVmView": [],
  "Onc.core.polymorphic.Association": [],
  "Onc.core.ui.widgets.Shell": [],
  "Onc.core.hub.Sync": [],
  "Onc.core.Proxy": [],
  "Ext.ux.ajax.SimManager": [],
  "Ext.ux.grid.filter.BooleanFilter": [],
  "Onc.view.Viewport": [],
  "Onc.view.tabs.VmListTab": [],
  "Onc.model.VmGridType": [],
  "Onc.controller.SearchController": [],
  "Ext.ux.TabScrollerMenu": [],
  "Ext.ux.IFrame": [],
  "Onc.model.Base": [],
  "Onc.view.tabs.VncTab": [],
  "Ext.ux.form.SearchField": [],
  "Onc.view.tabs.PortalTab": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.grid.filter.DateFilter": [],
  "Ext.ux.TreePicker": [],
  "Onc.model.ActionsContainer": [],
  "Onc.view.compute.ComputeHeaderView": [],
  "Onc.view.InfrastructureJoinView": [],
  "Onc.view.SearchResultsView": [],
  "Onc.core.hub.Hub": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "Ext.data.PagingMemoryProxy"
  ],
  "Onc.view.tabs.VmListGridTab": [],
  "Ext.ux.BoxReorderer": [],
  "Ext.ux.grid.filter.Filter": [],
  "Onc.view.tabs.Tab": [],
  "Onc.portal.PortalColumn": [],
  "Onc.core.ui.widgets.TagBox": [],
  "Onc.core.ui.components.DiskGauge": [],
  "Ext.ux.FieldReplicator": [],
  "Onc.model.AllocationPolicy": [],
  "Onc.view.OmsShellView": [],
  "Onc.controller.NewVmController": [],
  "Onc.controller.ZabbixRegistrationController": [],
  "Ext.ux.grid.filter.ListFilter": [],
  "Onc.view.tabs.NetworkTab": [],
  "Onc.controller.MigrateController": [],
  "Onc.model.Storage": [],
  "Onc.core.util.Completer": [],
  "Onc.controller.ComputeController": [],
  "Onc.core.ui.widgets.StaticTip": [
    "Ext.StaticTip"
  ],
  "Ext.ux.GMapPanel": [],
  "Onc.core.polymorphic.Reader": [],
  "Onc.store.NodesStore": [],
  "Onc.model.Templates": [],
  "Onc.controller.DashboardController": [],
  "Ext.ux.GroupTabPanel": [],
  "Ext.ux.DataView.LabelEditor": [],
  "Onc.store.RegisteredNodesStore": [],
  "Ext.ux.grid.filter.StringFilter": [],
  "Ext.ux.GroupTreeChunker": [],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Onc.controller.ComputeStateController": [],
  "Ext.ux.layout.Center": [],
  "Onc.core.Backend": [],
  "Onc.model.VirtualizationContainer": [],
  "Onc.store.PhysicalComputesStore": [],
  "Onc.core.manager.ComputeManager": [],
  "Ext.ux.DataView.Animated": [],
  "Onc.core.ui.widgets.Tagger": [],
  "Onc.core.util.Deferred": [],
  "Onc.model.SearchResult": [],
  "Ext.ux.statusbar.StatusBar": [
    "Ext.ux.StatusBar"
  ],
  "BridgeMembersStore": [],
  "Onc.view.LoginWindow": [],
  "Onc.store.GaugesChartComputesStore": [],
  "Onc.store.IncomingNodesStore": [],
  "Onc.core.ui.components.CPUGauge": [],
  "Onc.view.compute.ComputeStateControl": [],
  "Onc.view.tabs.VmMapTab": [],
  "Onc.core.ui.widgets.Vnc": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Onc.view.tabs.StorageTab": [],
  "Ext.ux.RowExpander": [],
  "Onc.view.tabs.ShellTab": [],
  "Onc.view.SearchFilterView": [],
  "Ext.ux.event.Player": [],
  "Onc.controller.EditVmController": [],
  "Onc.portal.PortalDropZone": [],
  "Onc.model.Template": [],
  "Onc.core.hub.Subscription": [],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.event.Maker": [],
  "Ext.ux.DataView.Draggable": [],
  "Onc.core.ui.widgets.TagModel": [],
  "Onc.portal.PortalPanel": [],
  "Ext.ux.TabCloseMenu": [],
  "Onc.view.tabs.TemplatesTab": [],
  "Onc.core.ui.components.MemoryGauge": [],
  "Onc.core.ui.widgets.InfoBox": [],
  "Onc.controller.NotificationBarController": [],
  "Onc.core.util.Scheduler": [],
  "Onc.view.tabs.DashboardTab": [],
  "Ext.ux.form.ItemSelector": [
    "Ext.ux.ItemSelector"
  ],
  "Ext.ux.ajax.JsonSimlet": [],
  "Ext.ux.Spotlight": [],
  "Ext.ux.grid.FiltersFeature": [],
  "Onc.controller.OmsShellController": [],
  "Onc.controller.MainController": []
});
Ext.ClassManager.addNameAliasMappings({
  "Onc.model.IpRoute": [],
  "Onc.model.Task": [],
  "Onc.model.ManagedNode": [],
  "Onc.view.compute.EditVmView": [
    "widget.editvm"
  ],
  "Onc.controller.TasksController": [],
  "Ext.ux.grid.TransformGrid": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Onc.store.VmGridTypeStore": [],
  "Onc.model.Hangar": [],
  "Onc.store.VirtualizationContainerStore": [],
  "Onc.model.NetworkInterface": [],
  "Onc.portal.GaugesChartPortlet": [
    "widget.gaugeschartportlet"
  ],
  "Onc.store.TasksPortletStore": [],
  "Onc.portal.LogPortlet": [
    "widget.logportlet"
  ],
  "Onc.model.VmProfile": [],
  "Ext.ux.event.Driver": [],
  "Ext.ux.ajax.XmlSimlet": [
    "simlet.xml"
  ],
  "Onc.store.VmProfilesStore": [],
  "Onc.store.SearchResultsStore": [],
  "Onc.view.compute.ComputeView": [
    "widget.computeview"
  ],
  "Onc.core.ui.components.NetworkGauge": [
    "widget.networkgauge"
  ],
  "Ext.ux.DataView.DragSelector": [],
  "Onc.view.compute.GaugesChartView": [
    "widget.gaugeschartview"
  ],
  "Onc.store.TasksStore": [],
  "Onc.view.compute.ZabbixRegistrationView": [
    "widget.zabbix"
  ],
  "Ext.ux.grid.menu.ListMenu": [],
  "Onc.portal.Portlet": [
    "widget.portlet"
  ],
  "Onc.view.TasksView": [
    "widget.tasksView"
  ],
  "Onc.store.TemplatesStore": [],
  "Onc.view.NotificationBarView": [
    "widget.notificationBar"
  ],
  "Ext.ux.form.MultiSelect": [
    "widget.multiselect",
    "widget.multiselectfield"
  ],
  "Onc.core.ui.widgets.GaugeChart": [
    "widget.gaugechart"
  ],
  "Onc.store.AllocationPolicyStore": [],
  "Onc.model.Command": [],
  "Onc.model.Compute": [],
  "Onc.model.NetworkInterfaces": [],
  "Ext.ux.CheckColumn": [
    "widget.checkcolumn"
  ],
  "Ext.ux.PreviewPlugin": [
    "plugin.preview"
  ],
  "Onc.portal.TasksPortlet": [
    "widget.tasksportlet"
  ],
  "Onc.model.ZabbixHostgroup": [],
  "Onc.store.VmGridStore": [],
  "Onc.core.ui.components.ComputeGauge": [
    "widget.computegauge"
  ],
  "Onc.store.ZabbixHostgroupsStore": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.event.RecorderManager": [
    "widget.eventrecordermanager"
  ],
  "Onc.store.ComputesStore": [],
  "Onc.model.AuthenticatedUser": [],
  "Onc.view.tabs.SystemTab": [
    "widget.computesystemtab"
  ],
  "Ext.ux.ProgressBarPager": [],
  "Onc.core.ui.widgets.Gauge": [
    "widget.gauge"
  ],
  "Ext.ux.ajax.Simlet": [
    "simlet.basic"
  ],
  "Ext.ux.SlidingPager": [],
  "Onc.core.Store": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [
    "gridfilter.numeric"
  ],
  "Onc.controller.InfrastructureJoinController": [],
  "Onc.controller.RetryController": [],
  "Onc.controller.LoginController": [],
  "Onc.core.EventBus": [],
  "Ext.ux.event.Recorder": [],
  "Onc.portal.InfoBoxesPortlet": [
    "widget.infoboxesportlet"
  ],
  "Onc.view.compute.NewVmView": [
    "widget.newvm"
  ],
  "Onc.core.polymorphic.Association": [
    "association.polymorphic"
  ],
  "Onc.core.ui.widgets.Shell": [
    "widget.shell"
  ],
  "Onc.core.hub.Sync": [],
  "Onc.core.Proxy": [
    "proxy.onc"
  ],
  "Ext.ux.ajax.SimManager": [],
  "Ext.ux.grid.filter.BooleanFilter": [
    "gridfilter.boolean"
  ],
  "Onc.view.Viewport": [],
  "Onc.view.tabs.VmListTab": [
    "widget.computevmlisttab"
  ],
  "Onc.model.VmGridType": [],
  "Onc.controller.SearchController": [],
  "Ext.ux.TabScrollerMenu": [
    "plugin.tabscrollermenu"
  ],
  "Ext.ux.IFrame": [
    "widget.uxiframe"
  ],
  "Onc.model.Base": [],
  "Onc.view.tabs.VncTab": [
    "widget.computevnctab"
  ],
  "Ext.ux.form.SearchField": [
    "widget.searchfield"
  ],
  "Onc.view.tabs.PortalTab": [
    "widget.portaltab"
  ],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.grid.filter.DateFilter": [
    "gridfilter.date"
  ],
  "Ext.ux.TreePicker": [
    "widget.treepicker"
  ],
  "Onc.model.ActionsContainer": [],
  "Onc.view.compute.ComputeHeaderView": [
    "widget.computeheader"
  ],
  "Onc.view.InfrastructureJoinView": [
    "widget.infrastructurejoin"
  ],
  "Onc.view.SearchResultsView": [
    "widget.searchresults"
  ],
  "Onc.core.hub.Hub": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "proxy.pagingmemory"
  ],
  "Onc.view.tabs.VmListGridTab": [
    "widget.computevmlistgridtab"
  ],
  "Ext.ux.BoxReorderer": [],
  "Ext.ux.grid.filter.Filter": [],
  "Onc.view.tabs.Tab": [],
  "Onc.portal.PortalColumn": [
    "widget.portalcolumn"
  ],
  "Onc.core.ui.widgets.TagBox": [
    "widget.tag"
  ],
  "Onc.core.ui.components.DiskGauge": [
    "widget.diskgauge"
  ],
  "Ext.ux.FieldReplicator": [],
  "Onc.model.AllocationPolicy": [],
  "Onc.view.OmsShellView": [
    "widget.omsShellView"
  ],
  "Onc.controller.NewVmController": [],
  "Onc.controller.ZabbixRegistrationController": [],
  "Ext.ux.grid.filter.ListFilter": [
    "gridfilter.list"
  ],
  "Onc.view.tabs.NetworkTab": [
    "widget.computenetworktab"
  ],
  "Onc.controller.MigrateController": [],
  "Onc.model.Storage": [],
  "Onc.core.util.Completer": [],
  "Onc.controller.ComputeController": [],
  "Onc.core.ui.widgets.StaticTip": [
    "widget.statictip"
  ],
  "Ext.ux.GMapPanel": [
    "widget.gmappanel"
  ],
  "Onc.core.polymorphic.Reader": [
    "reader.polymorphic"
  ],
  "Onc.store.NodesStore": [],
  "Onc.model.Templates": [],
  "Onc.controller.DashboardController": [],
  "Ext.ux.GroupTabPanel": [
    "widget.grouptabpanel"
  ],
  "Ext.ux.DataView.LabelEditor": [],
  "Onc.store.RegisteredNodesStore": [],
  "Ext.ux.grid.filter.StringFilter": [
    "gridfilter.string"
  ],
  "Ext.ux.GroupTreeChunker": [],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Onc.controller.ComputeStateController": [],
  "Ext.ux.layout.Center": [
    "layout.ux.center"
  ],
  "Onc.core.Backend": [],
  "Onc.model.VirtualizationContainer": [],
  "Onc.store.PhysicalComputesStore": [],
  "Onc.core.manager.ComputeManager": [],
  "Ext.ux.DataView.Animated": [],
  "Onc.core.ui.widgets.Tagger": [
    "widget.tagger"
  ],
  "Onc.core.util.Deferred": [],
  "Onc.model.SearchResult": [],
  "Ext.ux.statusbar.StatusBar": [
    "widget.statusbar"
  ],
  "BridgeMembersStore": [],
  "Onc.view.LoginWindow": [
    "widget.loginwindow"
  ],
  "Onc.store.GaugesChartComputesStore": [],
  "Onc.store.IncomingNodesStore": [],
  "Onc.core.ui.components.CPUGauge": [
    "widget.cpugauge"
  ],
  "Onc.view.compute.ComputeStateControl": [
    "widget.computestatecontrol"
  ],
  "Onc.view.tabs.VmMapTab": [
    "widget.computevmmaptab"
  ],
  "Onc.core.ui.widgets.Vnc": [
    "widget.vnc"
  ],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Onc.view.tabs.StorageTab": [
    "widget.computestoragetab"
  ],
  "Ext.ux.RowExpander": [
    "plugin.rowexpander"
  ],
  "Onc.view.tabs.ShellTab": [
    "widget.computeshelltab"
  ],
  "Onc.view.SearchFilterView": [
    "widget.searchfilter"
  ],
  "Ext.ux.event.Player": [],
  "Onc.controller.EditVmController": [],
  "Onc.portal.PortalDropZone": [],
  "Onc.model.Template": [],
  "Onc.core.hub.Subscription": [],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.event.Maker": [],
  "Ext.ux.DataView.Draggable": [],
  "Onc.core.ui.widgets.TagModel": [],
  "Onc.portal.PortalPanel": [
    "widget.portalpanel"
  ],
  "Ext.ux.TabCloseMenu": [
    "plugin.tabclosemenu"
  ],
  "Onc.view.tabs.TemplatesTab": [
    "widget.computetemplatestab"
  ],
  "Onc.core.ui.components.MemoryGauge": [
    "widget.memorygauge"
  ],
  "Onc.core.ui.widgets.InfoBox": [
    "widget.infobox"
  ],
  "Onc.controller.NotificationBarController": [],
  "Onc.core.util.Scheduler": [],
  "Onc.view.tabs.DashboardTab": [
    "widget.computedashboardtab"
  ],
  "Ext.ux.form.ItemSelector": [
    "widget.itemselector",
    "widget.itemselectorfield"
  ],
  "Ext.ux.ajax.JsonSimlet": [
    "simlet.json"
  ],
  "Ext.ux.Spotlight": [],
  "Ext.ux.grid.FiltersFeature": [
    "feature.filters"
  ],
  "Onc.controller.OmsShellController": [],
  "Onc.controller.MainController": []
});
