BACKEND_PREFIX = '';
ENABLE_VMMAP = true;
ENABLE_VMMAP_TOOLBAR = true;
ENABLE_VMMAP_REFRESH = true;
ENABLE_VMMAP_TAG = false;
ENABLE_VMMAP_RESIZE = false;
ENABLE_VMMAP_MIGRATE = true;
ENABLE_VMLIST_DELETE = false;
ENABLE_VNC = false;
ENABLE_ZABBIX = false;
ENABLE_VMMAP_LEGEND = false;

//FATAL, ERROR, WARN, INFO, DEBUG, and TRACE.
LOG_LEVEL = 'INFO';
